#!/bin/bash

output=`docker run --cap-add IPC_LOCK --rm -e VAULT_ADDR=http://host.docker.internal:8200 vault vault operator init`

unseal_key_1=`echo "${output}" | grep "Unseal Key 1" | awk -F'Unseal Key 1: ' '{print $2}'`
unseal_key_2=`echo "${output}" | grep "Unseal Key 2" | awk -F'Unseal Key 2: ' '{print $2}'`
unseal_key_3=`echo "${output}" | grep "Unseal Key 3" | awk -F'Unseal Key 3: ' '{print $2}'`
unseal_key_4=`echo "${output}" | grep "Unseal Key 4" | awk -F'Unseal Key 4: ' '{print $2}'`
unseal_key_5=`echo "${output}" | grep "Unseal Key 5" | awk -F'Unseal Key 5: ' '{print $2}'`

root_token=`echo "${output}" | grep "Initial Root Token" | awk -F'Initial Root Token: ' '{print $2}'`

echo "${unseal_key_1}" > secrets/vault_unseal_key_1
echo "${unseal_key_2}" > secrets/vault_unseal_key_2
echo "${unseal_key_3}" > secrets/vault_unseal_key_3
echo "${unseal_key_4}" > secrets/vault_unseal_key_4
echo "${unseal_key_5}" > secrets/vault_unseal_key_5

echo "${root_token}" > secrets/vault_root_token

UNSEAL_API="http://localhost:8200/v1/sys/unseal"

curl -d "{\"key\": \"${unseal_key_1}\"}" -X PUT $UNSEAL_API
curl -d "{\"key\": \"${unseal_key_2}\"}" -X PUT $UNSEAL_API
curl -d "{\"key\": \"${unseal_key_3}\"}" -X PUT $UNSEAL_API
